### ISSUE TITLE
Remove add song form from home page

### ISSUE THREAD

**Issue by PeterBell** [smithWEBtek/piano-cms#5]

**Comment by PeterBell** [comment]
This should be a link on the /students page to a form which should be songs/new

**Comment by smithWEBtek** [comment]
I've added '/students/new' with a separate page ( "students/new.html.erb"). 

But, I'm not entirely clear when you refer to "home" page, because the only user to see the current form for adding a song, would be the admin.    

The list of students, add a student, list of songs, add a song forms are there for admin to edit in one place.  

I've updated the students_controller to incorporate "Add new song" link for the /students page, where all students and their lists of songs are shown.

**Comment by PeterBell** [comment]
Hey @smithWEBtek want to schedule one more session for late this week or sometime next week for the two of us to pair on all this stuff? Not a requirement to pass, but free mentoring if you're interested!
Really appreciate how hard you're working on all of this!

**Comment by smithWEBtek** [comment]
Hi @peterbell
Yes please I would appreciate any mentoring time.

**Comment by PeterBell** [comment]
My bad - should have left this open
